#### Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for __Alexandre-
Theophile Vandermonde__.

### Problem statement 1

In linear algebra, a Vandermonde matrix, named after Alexandre-Théophile Vandermonde, is a matrix with the terms of a geometric progression in each row, i.e., an m × n matrix

<img src = 'Vandermonde matrix.png'>

In [1]:
import numpy as np

In [2]:
def gen_vandm_matrix(inpvec, N, is_increasing=False):
    
    """
    N = no of columns to take, N <= size of the input vector
    
    is_increasing is a boolean, default=False (decreasing order of powers), True = increasing order of powers
    
    inpvec is the input vector
    """
    
    if not is_increasing:
        op_matrix = np.array([x**(N-i-1) for x in inpvec for i in range(N)]).reshape((input_vec.size, N))
    elif is_increasing:
        op_matrix = np.array([x**i for x in inpvec for i in range(N)]).reshape((input_vec.size, N))
    
    return op_matrix

In [3]:
input_vec = np.array([1,2,3,4,5])

In [4]:
print("Vander matrix of the input array in decreasing order of powers:")

print(gen_vandm_matrix(input_vec, 3))

print('')

print("Vander matrix of the input array in increasing order of powers:")

print(gen_vandm_matrix(input_vec, 3, True))

Vander matrix of the input array in decreasing order of powers:
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]

Vander matrix of the input array in increasing order of powers:
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


### Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

<img src = 'problem2.png'>

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

#### Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
def find_moving_avg(inp_vec, k):

    n = inp_vec.size
    print('n')
    
    mov_avg_seq = np.zeros(n-k+1)
    
    for i in range(n-k+1):
        new_vec = inp_vec[i:k+i]
        avg = np.sum(new_vec)/k
        mov_avg_seq[i] = avg
        i += 1
        
    return mov_avg_seq

In [6]:
input_vec_n = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [7]:
find_moving_avg(input_vec_n, 3)

n


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])